### ISSUE TITLE
Road to v1.0.0

### ISSUE THREAD

**Issue by OrangeTux** [mobilityhouse/ocpp#174]
This is a meta issue to discuss and track progress to a v1.0.0.

A PR exist and is prepared and approved for v1.0.0:
- [x] #521 v201.enums.StatusInfoReasonType.invaild_schedule
- [x] #525 json schmemavalidation fails on type any - change configuration type incorrect
- [x] #522 Attributes with 'v2x' are serialized as 'V2x', but should be serialized as 'V2X' 
- [x] #529 2.0.1 dataclasses have a incorrect types that don't match carnality
- [x] #512 update to match Appendix 2. Standardized Units Of Measure 
- [x] #491 Typo in CostUpdated Action
- [x] #496 v201.datatypes.ChargingNeedsType.request_energy_transfer is mistyped
- [x] #497 v16/schemas/StopTransaction.json missing "Hertz" #207
- [x] #576 Remove support for ocpp 2.0
- [x] #577 Correct naming of members of v201.enums.AttributeType
- [x] #585 drop support for python 3.7 (#598 )
- [x] #591 Fix camel_to_snake_case for "v2x"
- [x] #575 Remove v1.6 deprecated enums variants
- [x] #578 Correct naming of members of v201.enums.AttributeType
- [x] #594 Fix camel_to_snake_case for "v2x"
- [x] #595 Update tests to use Call and CallResult without the suffix Payload
- [x] #596 OCPP 2.0.1 Wrong data type in CostUpdated total_cost
- [x] #606 Correct v2g serialisation/deserialisation
- [x] #527 The serialisation of soc to SoC should not occur in camel case if it is existing at the beginning of a field
- [x] #580 v2.0.1 Action enums corrected
- [x] #592 URL does not get converted from snake_case responder_url to camelCase responderURL
- [x ] #600 v1.6 Action Enum members corrected
- [x] #605 Introduce Experimental Module For v2.1
- [x] #607 Correct-SoC-to-be-uppercase-except-for-when-occurring-first-(python-mixed-case)
- [x] #547 Improve removal of optional fields that are None

A PR exist and requires review or approval:

-----------
The following enhancements can be considered, however, a PR is required:

----------
Not included in 1.0.0
- [ ] #172  **Add dataclasses for ChargingProfile and its constituents**
- [ ] #102 **Return CallError if Call fails to unpack**
~- [ ] #136 **Rewrite API for hooking into requests and responses.** Implementation is unknown, maybe #168?~

Note that this list can be changed

**Comment by OrangeTux** [comment]
I removed #136 from the list. The current routing system has it flaws, but I consider it "good enough". It gets the job done.

Rewriting the routing API would probably cause significant breaking changes that puts a massive burden users.

**Comment by Jared-Newell-Mobility** [comment]
See pre-release - https://github.com/mobilityhouse/ocpp/pull/611

**Comment by Jared-Newell-Mobility** [comment]
1.0.0-rc.1 released so will close
